### ISSUE TITLE
SubmissionMilestone.js  Button Card need to be small and black GridView 

### ISSUE THREAD

**Issue by ChathushkaRodrigo** [ChathushkaRodrigo/CDAP-PROJECT-MANAGEMENT-SYSTEM#214]
<img width="1512" alt="Screenshot 2022-08-14 at 23 45 17" src="https://user-images.githubusercontent.com/72795289/184549657-3c7d842a-3b43-4f23-ba5e-f97ed22a2baa.png">

**Comment by PasinduVinod** [comment]
Submission Milestone page front end styling completed!

**Comment by PasinduVinod** [comment]
![image](https://user-images.githubusercontent.com/79078972/185449723-a8efb086-789f-4e7d-8ccf-a2af3790c52f.png)
