### ISSUE TITLE
View Staff Form  , Improvements Card

### ISSUE THREAD

**Issue by ChathushkaRodrigo** [ChathushkaRodrigo/CDAP-PROJECT-MANAGEMENT-SYSTEM#219]
<img width="1512" alt="Screenshot 2022-08-14 at 23 57 30" src="https://user-images.githubusercontent.com/72795289/184550102-5e4063eb-ce61-4809-b853-3e75aabf7cea.png">

**Comment by PasinduVinod** [comment]
@ChathushkaRodrigo  View Staff Form , Improvements Card -> Done
![image](https://user-images.githubusercontent.com/79078972/185706533-e3b86621-7893-44f0-876e-c215221d3949.png)

**Comment by PasinduVinod** [comment]
done!
