### ISSUE TITLE
Matched supervisors -> Page styles refinement

### ISSUE THREAD

**Issue by PasinduVinod** [ChathushkaRodrigo/CDAP-PROJECT-MANAGEMENT-SYSTEM#222]
![image](https://user-images.githubusercontent.com/79078972/184550587-88c6ef53-8486-453c-a1b4-eaaa8e4c8a09.png)

**Comment by ChathushkaRodrigo** [comment]
<img width="1512" alt="Screenshot 2022-08-15 at 19 21 51" src="https://user-images.githubusercontent.com/72795289/184648247-fa8bb9e9-b69c-4a3e-a271-0c6db80924bb.png">
Styled pages
