### ISSUE TITLE
My Grades result in table (2cols)

### ISSUE THREAD

**Issue by ChathushkaRodrigo** [ChathushkaRodrigo/CDAP-PROJECT-MANAGEMENT-SYSTEM#262]
<img width="1512" alt="Screenshot 2022-08-22 at 12 15 17" src="https://user-images.githubusercontent.com/72795289/185856186-746760b9-e038-46cb-b1a2-0b15a5fced39.png">

**Comment by ChathushkaRodrigo** [comment]
@PasinduVinod

**Comment by PasinduVinod** [comment]
@ChathushkaRodrigo Done!
