### ISSUE TITLE
View Biddings Page STAFF height need to be long 

### ISSUE THREAD

**Issue by ChathushkaRodrigo** [ChathushkaRodrigo/CDAP-PROJECT-MANAGEMENT-SYSTEM#266]
<img width="1512" alt="Screenshot 2022-08-22 at 12 20 13" src="https://user-images.githubusercontent.com/72795289/185857042-ee16ad91-b3f9-4a4a-baa0-9476d52da246.png">

**Comment by PasinduVinod** [comment]
Done!
