### ISSUE TITLE
viewBidding supervisor

### ISSUE THREAD

**Issue by shas99** [ChathushkaRodrigo/CDAP-PROJECT-MANAGEMENT-SYSTEM#275]
@PasinduVinod View Bidding for supervisor needs to be styled
![Screenshot from 2022-08-25 23-09-51](https://user-images.githubusercontent.com/59775493/186732888-6958f906-2d1e-4e06-a629-2ec3689ef7d2.png)
.

**Comment by PasinduVinod** [comment]
Completed!
![image](https://user-images.githubusercontent.com/79078972/187164768-df0ee7df-9e7c-4c0b-8741-56fef38d2b77.png)
