### ISSUE TITLE
Needs a 404 Error Page for non-existing pages

### ISSUE THREAD

**Issue by ChathushkaRodrigo** [ChathushkaRodrigo/CDAP-PROJECT-MANAGEMENT-SYSTEM#71]
@PasinduVinod @Chamath99-bot check on this . I will also see on this

**Comment by shas99** [comment]
@ChathushkaRodrigo This feature has been completed. This issue can be closed.

**Comment by ChathushkaRodrigo** [comment]
Amazing Work @shas99  i have improved the UI a bit more on that <
<img width="1512" alt="Screenshot 2022-08-18 at 18 42 17" src="https://user-images.githubusercontent.com/72795289/185403408-a1969766-be3d-4b44-9732-f7301c910a87.png">
3
